// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivpwxgcxgvxympoqgsfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cHd4Z2N4Z3Z4eW1wb3Fnc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODA3MzcsImV4cCI6MjA2MDA1NjczN30.uTic8snsvmlmFT0MKKXdk7_73ed4jWw-50p5Kg7KYcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);